import express from 'express';
import NotificationLog from '../models/NotificationLog.js';
import NewsArticle from '../models/NewsArticle.js';
import User from '../models/User.js';
import { sendNewsAlertEmail } from '../services/emailService.js';
import { protect, protectStrict } from './authRoutes.js';

const router = express.Router();

// @route GET /api/notifications
router.get('/', protect, async (req, res) => {
    try {
        const logs = await NotificationLog.find({ userId: req.user._id })
            .sort({ createdAt: -1 })
            .limit(50);
        res.json(logs);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// @route POST /api/notifications/test-email
// Protected with protectStrict authentication
router.post('/test-email', protectStrict, async (req, res) => {
    try {
        const { category, targetEmail } = req.body;
        const recipient = targetEmail || req.user.email;

        let article = await NewsArticle.findOne({ category: category || 'Technology' }).sort({ publishedAt: -1 });
        if (!article) {
            article = {
                title: 'Test Breaking Alert: Artificial Intelligence System Passes Benchmark',
                description: 'This is a test notification generated by PulseNews Alert System to verify email delivery.',
                category: category || 'Technology',
                source: 'PulseNews Test Service',
                url: 'https://pulsenews.live/test-alert',
                publishedAt: new Date(),
            };
        }

        const emailResult = await sendNewsAlertEmail({
            toEmail: recipient,
            userTitle: req.user.name,
            article,
            unsubscribeToken: req.user.unsubscribeToken,
        });

        const log = new NotificationLog({
            userId: req.user._id,
            userEmail: recipient,
            articleTitle: article.title,
            category: article.category || 'Technology',
            source: article.source || 'PulseNews Wire',
            channel: 'Email',
            frequency: req.user.alertFrequency || 'Immediate',
            status: emailResult.success ? 'Sent' : 'Failed',
            previewUrl: emailResult.previewUrl,
        });
        await log.save();

        res.json({
            message: `Test email dispatched to ${recipient}`,
            success: emailResult.success,
            previewUrl: emailResult.previewUrl,
            log,
        });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// @route GET or POST /api/notifications/unsubscribe
// Allows single-click unsubscribe from alert emails
const handleUnsubscribe = async (req, res) => {
    try {
        const email = req.query.email || req.body.email;
        const token = req.query.token || req.body.token;

        if (!email && !token) {
            return res.status(400).send('<h3>Invalid Unsubscribe Request</h3><p>Missing email parameter.</p>');
        }

        let user;
        if (token) {
            user = await User.findOne({ unsubscribeToken: token });
        }
        if (!user && email) {
            user = await User.findOne({ email: email.toLowerCase().trim() });
        }

        if (!user) {
            return res.status(404).send('<h3>User Not Found</h3><p>No active subscription found for this email address.</p>');
        }

        user.channels.email = false;
        await user.save();

        res.send(`
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <title>Unsubscribed - PulseNews</title>
                <style>
                    body { font-family: system-ui, sans-serif; background-color: #0f172a; color: #f8fafc; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; }
                    .card { background: #1e293b; padding: 36px; border-radius: 16px; border: 1px solid #334155; text-align: center; max-width: 480px; }
                    h2 { color: #f43f5e; margin-top: 0; }
                    p { color: #94a3b8; line-height: 1.6; }
                    a { display: inline-block; background: #3b82f6; color: #fff; padding: 10px 20px; border-radius: 8px; text-decoration: none; font-weight: 600; margin-top: 16px; }
                </style>
            </head>
            <body>
                <div class="card">
                    <h2>Unsubscribed Successfully</h2>
                    <p>You have been unsubscribed from PulseNews email breaking alerts and digests for <strong>${user.email}</strong>.</p>
                    <p>You can re-enable email alerts anytime in your account Preferences.</p>
                    <a href="http://localhost:5173/preferences">Return to PulseNews Preferences</a>
                </div>
            </body>
            </html>
        `);
    } catch (error) {
        res.status(500).send(`<h3>Error</h3><p>${error.message}</p>`);
    }
};

router.get('/unsubscribe', handleUnsubscribe);
router.post('/unsubscribe', handleUnsubscribe);

// @route POST /api/notifications/subscribe-push
// Register Web Push subscription for authenticated user
router.post('/subscribe-push', protect, async (req, res) => {
    try {
        const { subscription } = req.body;
        if (!subscription || !subscription.endpoint) {
            return res.status(400).json({ message: 'Invalid push subscription details' });
        }

        req.user.pushSubscription = subscription;
        req.user.channels.push = true;
        await req.user.save();

        res.json({ message: 'Web Push subscription registered successfully.', pushEnabled: true });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// @route PUT /api/notifications/:id/read
router.put('/:id/read', protect, async (req, res) => {
    try {
        const log = await NotificationLog.findById(req.params.id);
        if (!log) return res.status(404).json({ message: 'Log not found' });

        log.status = 'Read';
        log.readAt = new Date();
        await log.save();

        res.json(log);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

export default router;
