import express from 'express';
import NotificationLog from '../models/NotificationLog.js';
import NewsArticle from '../models/NewsArticle.js';
import { sendNewsAlertEmail } from '../services/emailService.js';
import { protect } from './authRoutes.js';

const router = express.Router();

// @route GET /api/notifications
router.get('/', protect, async (req, res) => {
    try {
        const logs = await NotificationLog.find({ userId: req.user._id })
            .sort({ createdAt: -1 })
            .limit(50);
        res.json(logs);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// @route POST /api/notifications/test-email
router.post('/test-email', protect, async (req, res) => {
    try {
        const { category, targetEmail } = req.body;
        const recipient = targetEmail || req.user.email;

        // Pick latest article in category or generate placeholder
        let article = await NewsArticle.findOne({ category: category || 'Technology' }).sort({ publishedAt: -1 });
        if (!article) {
            article = {
                title: 'Test Breaking Alert: Artificial Intelligence System Passes Benchmark',
                description: 'This is a test notification generated by PulseNews Alert System to verify Nodemailer integration.',
                category: category || 'Technology',
                source: 'PulseNews Test Service',
                url: 'https://pulsenews.live/test-alert',
                publishedAt: new Date(),
            };
        }

        const emailResult = await sendNewsAlertEmail({
            toEmail: recipient,
            userTitle: req.user.name,
            article,
        });

        const log = new NotificationLog({
            userId: req.user._id,
            userEmail: recipient,
            articleTitle: article.title,
            category: article.category || 'Technology',
            source: article.source || 'PulseNews Wire',
            channel: 'Email',
            frequency: req.user.alertFrequency || 'Immediate',
            status: emailResult.success ? 'Sent' : 'Failed',
            previewUrl: emailResult.previewUrl,
        });
        await log.save();

        res.json({
            message: `Test email dispatched to ${recipient}`,
            success: emailResult.success,
            previewUrl: emailResult.previewUrl,
            log,
        });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// @route PUT /api/notifications/:id/read
router.put('/:id/read', protect, async (req, res) => {
    try {
        const log = await NotificationLog.findById(req.params.id);
        if (!log) return res.status(404).json({ message: 'Log not found' });

        log.status = 'Read';
        log.readAt = new Date();
        await log.save();

        res.json(log);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

export default router;
